name: "CxOne SAST Scan"

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  CxOne:
    uses: "Security-Testing/security-tools-workflows/.github/workflows/cxone.yml@main"
    secrets: inherit
    permissions:
      contents: read
      id-token: write
      pull-requests: write # needed for the scan summary in PRs      
      # The following permissions are required only if you want to upload a SARIF file to GitHub for code scanning results.
      # This upload is NOT performed by default. To enable it, set the 'github-upload' parameter to true.
      # If you do not intend to upload SARIF to GitHub, you can safely remove these extra permissions.
      security-events: write
      actions: read
